//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Entity.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ImportScenarioVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImportScenarioVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Entity.Properties.ImportScenarioVN", typeof(ImportScenarioVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string fieldNameAddress {
            get {
                return ResourceManager.GetString("fieldNameAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thẻ thành viên.
        /// </summary>
        public static string fieldNameCard {
            get {
                return ResourceManager.GetString("fieldNameCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng (*).
        /// </summary>
        public static string fieldNameCode {
            get {
                return ResourceManager.GetString("fieldNameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên công ty.
        /// </summary>
        public static string fieldNameCompany {
            get {
                return ResourceManager.GetString("fieldNameCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string fieldNameDescription {
            get {
                return ResourceManager.GetString("fieldNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string fieldNameDob {
            get {
                return ResourceManager.GetString("fieldNameDob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string fieldNameEmail {
            get {
                return ResourceManager.GetString("fieldNameEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm khách hàng.
        /// </summary>
        public static string fieldNameGroup {
            get {
                return ResourceManager.GetString("fieldNameGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khách hàng (*).
        /// </summary>
        public static string fieldNameName {
            get {
                return ResourceManager.GetString("fieldNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string fieldNamePhone {
            get {
                return ResourceManager.GetString("fieldNamePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế.
        /// </summary>
        public static string fieldNameTax {
            get {
                return ResourceManager.GetString("fieldNameTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  đã tồn tại trong file danh sách..
        /// </summary>
        public static string messageErrorDuplicateList {
            get {
                return ResourceManager.GetString("messageErrorDuplicateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  đã tồn tại trong hệ thống..
        /// </summary>
        public static string messageErrorDuplicateSystem {
            get {
                return ResourceManager.GetString("messageErrorDuplicateSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  không đúng định dạng..
        /// </summary>
        public static string messageErrorFormat {
            get {
                return ResourceManager.GetString("messageErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  không được phép để trống..
        /// </summary>
        public static string messageErrorRequired {
            get {
                return ResourceManager.GetString("messageErrorRequired", resourceCulture);
            }
        }
    }
}
