//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Entity.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Entity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa thông tin khách hàng, kiểm tra lại ID nhé..
        /// </summary>
        public static string messageErrorCustomerDelete_Dev {
            get {
                return ResourceManager.GetString("messageErrorCustomerDelete_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa thông tin khách hàng..
        /// </summary>
        public static string messageErrorCustomerDelete_User {
            get {
                return ResourceManager.GetString("messageErrorCustomerDelete_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy dữ liệu khách hàng..
        /// </summary>
        public static string messageErrorCustomerGetAll_Dev {
            get {
                return ResourceManager.GetString("messageErrorCustomerGetAll_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy dữ liệu khách hàng..
        /// </summary>
        public static string messageErrorCustomerGetAll_User {
            get {
                return ResourceManager.GetString("messageErrorCustomerGetAll_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy dữ liệu khách hàng này, kiểm tra ID nhé..
        /// </summary>
        public static string messageErrorCustomerGetById_Dev {
            get {
                return ResourceManager.GetString("messageErrorCustomerGetById_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy dữ liệu khách hàng..
        /// </summary>
        public static string messageErrorCustomerGetById_User {
            get {
                return ResourceManager.GetString("messageErrorCustomerGetById_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thêm dữ liệu khách hàng, kiểm tra các trường nhé..
        /// </summary>
        public static string messageErrorCustomerInsert_Dev {
            get {
                return ResourceManager.GetString("messageErrorCustomerInsert_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thêm dữ liệu khách hàng..
        /// </summary>
        public static string messageErrorCustomerInsert_User {
            get {
                return ResourceManager.GetString("messageErrorCustomerInsert_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật dữ liệu khách hàng, kiểm tra các trường nhé và nhớ validate..
        /// </summary>
        public static string messageErrorCustomerUpdate_Dev {
            get {
                return ResourceManager.GetString("messageErrorCustomerUpdate_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật dữ liệu khách hàng..
        /// </summary>
        public static string messageErrorCustomerUpdate_User {
            get {
                return ResourceManager.GetString("messageErrorCustomerUpdate_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa thông tin nhân viên, kiểm tra lại ID nhé..
        /// </summary>
        public static string messageErrorEmployeeDelete_Dev {
            get {
                return ResourceManager.GetString("messageErrorEmployeeDelete_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa thông tin nhân viên..
        /// </summary>
        public static string messageErrorEmployeeDelete_User {
            get {
                return ResourceManager.GetString("messageErrorEmployeeDelete_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy dữ liệu nhân viên..
        /// </summary>
        public static string messageErrorEmployeeGetAll_Dev {
            get {
                return ResourceManager.GetString("messageErrorEmployeeGetAll_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy dữ liệu nhân viên..
        /// </summary>
        public static string messageErrorEmployeeGetAll_User {
            get {
                return ResourceManager.GetString("messageErrorEmployeeGetAll_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy dữ liệu nhân viên này, kiểm tra ID nhé..
        /// </summary>
        public static string messageErrorEmployeeGetById_Dev {
            get {
                return ResourceManager.GetString("messageErrorEmployeeGetById_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy dữ liệu nhân viên..
        /// </summary>
        public static string messageErrorEmployeeGetById_User {
            get {
                return ResourceManager.GetString("messageErrorEmployeeGetById_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thêm dữ liệu nhân viên, kiểm tra các trường nhé..
        /// </summary>
        public static string messageErrorEmployeeInsert_Dev {
            get {
                return ResourceManager.GetString("messageErrorEmployeeInsert_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thêm dữ liệu nhân viên..
        /// </summary>
        public static string messageErrorEmployeeInsert_User {
            get {
                return ResourceManager.GetString("messageErrorEmployeeInsert_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật dữ liệu nhân viên, kiểm tra các trường nhé và nhớ validate..
        /// </summary>
        public static string messageErrorEmployeeUpdate_Dev {
            get {
                return ResourceManager.GetString("messageErrorEmployeeUpdate_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật dữ liệu nhân viên..
        /// </summary>
        public static string messageErrorEmployeeUpdate_User {
            get {
                return ResourceManager.GetString("messageErrorEmployeeUpdate_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu khách hàng thành công..
        /// </summary>
        public static string messageSuccessCustomerDelete {
            get {
                return ResourceManager.GetString("messageSuccessCustomerDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm dữ liệu khách hàng thành công..
        /// </summary>
        public static string messageSuccessCustomerInsert {
            get {
                return ResourceManager.GetString("messageSuccessCustomerInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật dữ liệu khách hàng thành công..
        /// </summary>
        public static string messageSuccessCustomerUpdate {
            get {
                return ResourceManager.GetString("messageSuccessCustomerUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu nhân viên thành công..
        /// </summary>
        public static string messageSuccessEmployeeDelete {
            get {
                return ResourceManager.GetString("messageSuccessEmployeeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm dữ liệu nhân viên thành công..
        /// </summary>
        public static string messageSuccessEmployeeInsert {
            get {
                return ResourceManager.GetString("messageSuccessEmployeeInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật dữ liệu nhân viên thành công..
        /// </summary>
        public static string messageSuccessEmployeeUpdate {
            get {
                return ResourceManager.GetString("messageSuccessEmployeeUpdate", resourceCulture);
            }
        }
    }
}
