//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Entity.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Entity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa thông tin, kiểm tra lại ID nhé..
        /// </summary>
        public static string messageErrorDelete_Dev {
            get {
                return ResourceManager.GetString("messageErrorDelete_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa thông tin..
        /// </summary>
        public static string messageErrorDelete_User {
            get {
                return ResourceManager.GetString("messageErrorDelete_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đã tồn tại trong hệ thống, vui lòng kiểm tra lại..
        /// </summary>
        public static string messageErrorDuplicateCode {
            get {
                return ResourceManager.GetString("messageErrorDuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng đã tồn tại trong hệ thống..
        /// </summary>
        public static string messageErrorDuplicateCodeCus {
            get {
                return ResourceManager.GetString("messageErrorDuplicateCodeCus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại trong hệ thống..
        /// </summary>
        public static string messageErrorDuplicateCodeEm {
            get {
                return ResourceManager.GetString("messageErrorDuplicateCodeEm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMND của nhân viên đã tồn tại trong hệ thống..
        /// </summary>
        public static string messageErrorDuplicateIdentityEm {
            get {
                return ResourceManager.GetString("messageErrorDuplicateIdentityEm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng, vui lòng kiểm tra lại..
        /// </summary>
        public static string messageErrorEmailFormat {
            get {
                return ResourceManager.GetString("messageErrorEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy dữ liệu nhân viên này, kiểm tra ID nhé..
        /// </summary>
        public static string messageErrorEmployeeGetById_Dev {
            get {
                return ResourceManager.GetString("messageErrorEmployeeGetById_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy dữ liệu nhân viên..
        /// </summary>
        public static string messageErrorEmployeeGetById_User {
            get {
                return ResourceManager.GetString("messageErrorEmployeeGetById_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thêm dữ liệu nhân viên, kiểm tra các trường nhé..
        /// </summary>
        public static string messageErrorEmployeeInsert_Dev {
            get {
                return ResourceManager.GetString("messageErrorEmployeeInsert_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thêm dữ liệu nhân viên..
        /// </summary>
        public static string messageErrorEmployeeInsert_User {
            get {
                return ResourceManager.GetString("messageErrorEmployeeInsert_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật dữ liệu nhân viên, kiểm tra các trường nhé và nhớ validate..
        /// </summary>
        public static string messageErrorEmployeeUpdate_Dev {
            get {
                return ResourceManager.GetString("messageErrorEmployeeUpdate_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật dữ liệu nhân viên..
        /// </summary>
        public static string messageErrorEmployeeUpdate_User {
            get {
                return ResourceManager.GetString("messageErrorEmployeeUpdate_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy dữ liệu..
        /// </summary>
        public static string messageErrorGetAll_Dev {
            get {
                return ResourceManager.GetString("messageErrorGetAll_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy dữ liệu..
        /// </summary>
        public static string messageErrorGetAll_User {
            get {
                return ResourceManager.GetString("messageErrorGetAll_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy dữ liệu này, kiểm tra ID nhé..
        /// </summary>
        public static string messageErrorGetById_Dev {
            get {
                return ResourceManager.GetString("messageErrorGetById_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy dữ liệu..
        /// </summary>
        public static string messageErrorGetById_User {
            get {
                return ResourceManager.GetString("messageErrorGetById_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thêm dữ liệu, kiểm tra các trường nhé..
        /// </summary>
        public static string messageErrorInsert_Dev {
            get {
                return ResourceManager.GetString("messageErrorInsert_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thêm dữ liệu..
        /// </summary>
        public static string messageErrorInsert_User {
            get {
                return ResourceManager.GetString("messageErrorInsert_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File xls hoặc xlsx không hợp lệ..
        /// </summary>
        public static string messageErrorNullFile {
            get {
                return ResourceManager.GetString("messageErrorNullFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy dữ liệu phân trang khách hàng..
        /// </summary>
        public static string messageErrorPagingFilterCus {
            get {
                return ResourceManager.GetString("messageErrorPagingFilterCus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy dữ liệu phân trang nhân viên..
        /// </summary>
        public static string messageErrorPagingFilterEm {
            get {
                return ResourceManager.GetString("messageErrorPagingFilterEm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật dữ liệu, kiểm tra các trường nhé và nhớ validate..
        /// </summary>
        public static string messageErrorUpdate_Dev {
            get {
                return ResourceManager.GetString("messageErrorUpdate_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật dữ liệu..
        /// </summary>
        public static string messageErrorUpdate_User {
            get {
                return ResourceManager.GetString("messageErrorUpdate_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu thành công..
        /// </summary>
        public static string messageSuccessDelete {
            get {
                return ResourceManager.GetString("messageSuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật dữ liệu nhân viên thành công..
        /// </summary>
        public static string messageSuccessEmployeeUpdate {
            get {
                return ResourceManager.GetString("messageSuccessEmployeeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm dữ liệu thành công..
        /// </summary>
        public static string messageSuccessInsert {
            get {
                return ResourceManager.GetString("messageSuccessInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật dữ liệu thành công..
        /// </summary>
        public static string messageSuccessUpdate {
            get {
                return ResourceManager.GetString("messageSuccessUpdate", resourceCulture);
            }
        }
    }
}
